### ISSUE TITLE
No funciona, al pulsar f la consola devuelve ReferenceError: swal is not defined

### ISSUE THREAD

**Issue by liam-maps** [Pytness/fc-script#35]
El error lo marca en la función **function showPopPup()** en la línea **return swal({**, pero no tengo ni puta idea de javascript, así que no se arreglarlo.

**Comment by Pytness** [comment]
Has modificado algo del script? Acabo de instalarlo y me funciona perfectamente.
Mira a ver si se soluciona reinstalando el script o en su defecto reinstalando tampermonkey.
Tambien me vendria bien que me dijeses que navegador utilizas.

**Comment by liam-maps** [comment]
Hola.
Gracias por contestar. 
El problema que te comento es con el script de ocultar hilos por palabras clave.
El problema me lo da en la última versión de firefox en Windows 10 usando Violentmonkey.
He probado greasemonkey y tampoco funciona, pero el error es que jQuery no está definido.
Con tampermonkey sí parece funcionar.
Un saludo.
